name: Publish Test App

on:
  push:
    branches: [ publish ]

jobs:
  publish-fat-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Upload Bintray Test App
        uses: GabrielBB/xvfb-action@v1.2
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        with:
          run: ./gradlew bintrayUp

  publish-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Upload Bintray Test App
        uses: GabrielBB/xvfb-action@v1.2
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        with:
          run: ./gradlew bintrayUp -PbintrayBinaries

  publish-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Upload Bintray Test App
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew bintrayUp -PbintrayBinaries

  publish-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Upload Bintray Test App
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew bintrayUp -PbintrayBinaries
